[pytest]
testpaths = tests
addopts = --html=reports/report.html --self-contained-html -v
markers =
    functional: Functional test cases
    regression: Regression test cases
    auth: Authentication tests